---
title: 13 마크다운으로 데이터 분석 보고서 만들기
jupyter:
  jupytext:
    cell_metadata_filter: 'eval,-all'
    notebook_metadata_filter: '-all'
  kernelspec:
    display_name: Python 3 (ipykernel)
    language: python
    name: python3
---


## 13-1 신뢰할 수 있는 데이터 분석 보고서 만들기


## 13-2 마크다운 문서 만들기

### (Do it! 실습) 마크다운 문서 만들기

# 데이터 분석 보고서 만들기

## 마크다운

마크다운 문법으로 코드를 작성해 [HTML](https://ko.wikipedia.org/wiki/HTML)로 변환할 수 있습니다.

---

# 데이터 분석 보고서 만들기

## 마크다운

마크다운 문법으로 코드를 작성해 [HTML](https://ko.wikipedia.org/wiki/HTML)로 변환할 수 있습니다.

---
---

### (Do it! 실습) 마크다운 문법 이용하기

문자 앞뒤에 *특수문자*를 넣으면 기울임체가 됩니다.

문자 앞뒤에 **특수문자**를 넣으면 강조체가 됩니다.

문자 앞뒤에 ~~특수문자~~를 넣으면 취소선을 만듭니다.

문자 앞뒤에 [특수문자](http://www.google.com/search?q=special+character)를 넣으면 하이퍼링크를 만듭니다.

# 1 단계 제목
## 2 단계 제목
### 3 단계 제목
#### 4 단계 제목

코드에 백틱 기호를 입력하면 `pandas`와 같이 음영을 넣습니다.

---

문자 앞뒤에 *특수문자*를 넣으면 기울임체가 됩니다.

문자 앞뒤에 **특수문자**를 넣으면 강조체가 됩니다.

문자 앞뒤에 ~~특수문자~~를 넣으면 취소선을 만듭니다.

문자 앞뒤에 [특수문자](http://www.google.com/search?q=special+character)를 넣으면 하이퍼링크를 만듭니다.

# 1 단계 제목
## 2 단계 제목
### 3 단계 제목
#### 4 단계 제목

코드에 백틱 기호를 입력하면 `pandas`와 같이 음영을 넣습니다.

---
---

### (Do it! 실습) 마크다운으로 데이터 분석 보고서 만들기

# 데이터 분석 보고서 만들기

## 마크다운

마크다운 문법으로 코드를 작성해 [HTML](https://ko.wikipedia.org/wiki/HTML)로 변환할 수 있습니다. 마크다운을 이용하면 분석 과정과 결과를 자세하게 기술할 수 있어서 **재현 가능성**을 갖춘 *데이터 분석 보고서*를 만들 수 있습니다.

### 마크다운 문법 예제 

코드와 코드 실행 결과물을 보고서에 함께 출력합니다.

import pandas as pd
df = pd.read_csv('mpg.csv')
df['drv'].value_counts()

import seaborn as sns
sns.countplot(data = df, x = 'drv')

---

# 데이터 분석 보고서 만들기

## 마크다운

마크다운 문법으로 코드를 작성해 [HTML](https://ko.wikipedia.org/wiki/HTML)로 변환할 수 있습니다. 마크다운을 이용하면 분석 과정과 결과를 자세하게 기술할 수 있어서 **재현 가능성**을 갖춘 *데이터 분석 보고서*를 만들 수 있습니다.

### 마크다운 문법 예제 

코드와 코드 실행 결과물을 보고서에 함께 출력합니다.

```{python}
import pandas as pd
df = pd.read_csv('mpg.csv')
df['drv'].value_counts()
```

```{python}
#| tags: []
import seaborn as sns
sns.countplot(data = df, x = 'drv')
```

---
---

### (Do it! 실습) 문서 파일로 저장하기

**워드 파일로 저장하기**

```{python}
#| eval: false
# !pandoc report.ipynb -s -o report.docx
```

